<h2>new static vs new self</h2>
<pre>
*class Foo
{
   public static function baz() {
      return new self();
   }
}

$x = Foo::baz();  // $x is now a `Foo`

class Bar extends Foo
{
}

$z = Bar::baz();  // $z is now a `Foo`


*class Foo
{
   public static function baz() {
      return new static();
   }
}

class Bar extends Foo
{
}

$wow = Bar::baz();  // $wow is now a `Bar`, even though `baz()` is in base `Foo`
</pre>
<hr>
<h2>Only one object is created</h2>
<pre>
//singelton - only one object is created
class baskett{
	private static $instance;
	private function __construct(){
		echo 'bbbb';
	}
	public static function getInstance(){
		//when ever we call to this function if instance is not defined it will create and store in "instance", for every subsequent call it will always return the instance is stored
		if(!self::$instance){
		self::$instance = new static();
		}else{
			echo 'Using existing object';
		}
		return self::$instance;
	}
	public function set($key,$value){
		$this->$key = $value;
	}
	public function get($key){
		return $this->$key;
	}
	public function test(){
		echo "test";
	}
}

//$a = new baskett();
$a = baskett::getInstance();
//$a->set('a', 'aa');
//$a->set('b', 'bb');
//var_dump($a);

//echo $a->test();

//echo '<br>';

//$ab = new baskett();
$ab	 = baskett::getInstance();
//$ab->set('ab', 'aabb');
//var_dump($ab);

//echo $ab->test();

</pre>
<hr>
<h2>Exception Handling</h2>
<pre>
//create function with an exception
function checkNum($number) {
  if($number>1) {
    throw new Exception("Value must be 1 or below");
  }
  return true;
}

//trigger exception
checkNum(2);
</pre>
When an exception is thrown, the code following it will not be executed, and PHP will try to find the matching "catch" block.

If an exception is not caught, a fatal error will be issued with an "Uncaught Exception" message.

Fatal error: Uncaught Exception: Value must be 1 or below in D:\xamp\htdocs\xampp_test.php:5 Stack trace: #0 D:\xamp\htdocs\xampp_test.php(11): checkNum(2) #1 {main} thrown in D:\xamp\htdocs\xampp_test.php on line 5

Stack trace: #0 - This shows were the function is called which is throwning the expection.
Stack trace: #1 - This shows were the throw exception line is 
<hr>
<h2>PHP double quotes vs single quotes</h2>
<pre>
echo 'This is \'test\' string';   
//Output: This is 'test' string

$count = 1;
echo "The count is $count";
//Output: The count is 1

$count = 1;
echo 'The count is $count';
//Output: The count is $count

I recommend using single quotes (‘ ‘) for string unless we need the double quotes (” “). This is because double quotes forces PHP to evaluate(checks) the string (even though it might not be needed), whereas string between single quotes is not evaluated. Also, parsing variables between strings takes more memory than concatenation.

So instead of this:
$count = 1;
echo "The count is $count";

use this:
$count = 1;
echo 'The count is ' . $count;

</pre>
